job4u-postulation-symfony/src/Entity/Postulation.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\PostulationRepository;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PostulationRepository::class)]
class Postulation implements \JsonSerializable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $idPos = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "adresse is required")]
    private ?string $adresse = null;


    #[ORM\Column(length: 50)]
    #[Assert\NotBlank(message: "Email is required")]
    #[Assert\Email(message: "The email '{{ value }}' is not a valid email ")]
    private ?string $email = null;


    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank(message: "Date of the event not assigned")]
    private ?\DateTimeInterface $date_pos = null;

    #[ORM\ManyToOne(inversedBy: 'creator')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Users $creator = null;


    public function __construct()
    {
        $this->societe = new ArrayCollection();
    }

    public function getIdPos(): ?int
    {
        return $this->idPos;
    }

    public function setIdPos(): ?int
    {
        return $this->idPos;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }


    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDatePos(): ?\DateTimeInterface
    {
        return $this->date_pos;
    }

    public function setDatePos(\DateTimeInterface $date_pos): self
    {
        $this->date_pos = $date_pos;

        return $this;
    }

    public function getCreator(): ?Users
    {
        return $this->creator;
    }

    public function setCreator(?Users $creator): self
    {
        $this->creator = $creator;

        return $this;
    }


    /**
     * @return Collection<int, societe>
     */
    public function getSociete(): Collection
    {
        return $this->societe;
    }

    public function addSociete(societe $societe): self
    {
        if (!$this->societe->contains($societe)) {
            $this->societe->add($societe);
            $societe->setPostulation($this);
        }

        return $this;
    }

    public function removeSociete(societe $societe): self
    {
        if ($this->societe->removeElement($societe)) {
            // set the owning side to null (unless already changed)
            if ($societe->getPostulation() === $this) {
                $societe->setPostulation(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getEmail(); // or any other property you want to output
    }

    public function jsonSerialize(): array
    {
        return array(
            'id' => $this->idPos,
            'user' => $this->creator,
            'adresse' => $this->adresse,
            'email' => $this->email,
            'date' => $this->date_pos->format("d-m-Y")
        );
    }

    public function constructor($user, $adresse, $email, $date)
    {
        $this->creator = $user;
        $this->adresse = $adresse;
        $this->email = $email;
        $this->date_pos = $date;
    }
}

job4u-postulation-symfony/src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\DBAL\Types\Types;
use App\Form\SearchType;
#[ORM\Entity(repositoryClass: UsersRepository::class)]
class Users implements \JsonSerializable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 33)]
    private ?string $Nom = null;

    #[ORM\Column(length: 33)]
    private ?string $Prenom = null;

    #[ORM\Column(length: 40)]
    private ?string $Mail = null;

    #[ORM\Column(length: 33)]
    private ?string $Password = null;

    #[ORM\Column(length: 12)]
    private ?string $Role = null;

    #[ORM\OneToMany(mappedBy: 'creator', targetEntity: Postulation::class)]

    private Collection $creator;

    public function __construct()
    {
        $this->creator = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->Mail;
    }

    public function setMail(string $Mail): self
    {
        $this->Mail = $Mail;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->Password;
    }

    public function setPassword(string $Password): self
    {
        $this->Password = $Password;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->Role;
    }

    public function setRole(string $Role): self
    {
        $this->Role = $Role;

        return $this;
    }

    /**
     * @return Collection<int, Postulation>
     */
    public function getCreator(): Collection
    {
        return $this->creator;
    }

    public function addCreator(Postulation $creator): self
    {
        if (!$this->creator->contains($creator)) {
            $this->creator->add($creator);
            $creator->setCreator($this);
        }

        return $this;
    }

    public function removeCreator(Postulation $creator): self
    {
        if ($this->creator->removeElement($creator)) {
            // set the owning side to null (unless already changed)
            if ($creator->getCreator() === $this) {
                $creator->setCreator(null);
            }
        }

        return $this;
    }
    public function __toString() {
        return $this->getNom();
    }

    public function jsonSerialize(): array
    {
        return array(
            'id' => $this->id,
            'email' => $this->Mail
        );
    }

    public function constructor($email)
    {
        $this->Mail = $email;
    }
}

job4u-postulation-symfony/src/Controller/PostulationController.php
<?php

namespace App\Controller;
use App\Entity\Postulation;
use App\Form\PosType;
use App\Entity\Users;
use App\service\pdfService;
use Dompdf\Dompdf;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Dompdf\Options;
use App\Repository\PostulationRepository;
use App\Repository\UsersRepository;
use App\Form\SearchType;
use App\Form\ContactType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Contracts\Cache\CacheInterface;
 use Symfony\Component\Cache\CacheItem;
 use Psr\Cache\CacheItemInterface as ItemInterface;
 use Doctrine\ORM\EntityManagerInterface;use Symfony\Component\Serializer\Normalizer\DateTimeNormalizer;
 use Symfony\Component\Serializer\SerializerInterface;
 use Symfony\UX\Chartjs\Builder\ChartBuilderInterface;
 use Symfony\UX\Chartjs\Model\Chart;

class PostulationController extends AbstractController
{
    #[Route('/', name: 'display_pos')]
    public function index(Request $request, CacheInterface $cache): Response
    {
    //$texte = $cache->get('texte_detailss', function (ItemInterface $item) {
       // $item->expiresAfter(20);
       // return $this->fonctionLongue();
   // });

    //$pos = $this->getDoctrine()->getManager()->getRepository(Postulation::class)->findAll();
    $pos=$cache->get('postulation',function(ItemInterface $item){
        $item->expiresAfter(20);
        return $pos = $this->getDoctrine()->getManager()->getRepository(Postulation::class)->findAll();
    });
    return $this->render('postulation/index.html.twig', [
        'p' => $pos,
    ]);
}
    #[Route('/pos', name: 'display')]
    public function displayPostulations(Request $request, PaginatorInterface $paginator, PostulationRepository $postulationRepository): Response
    {  
    $queryBuilder = $postulationRepository->createQueryBuilder('p')
        ->orderBy('p.idPos', 'DESC')
        ->getQuery();
    
    $postulations = $paginator->paginate(
        $queryBuilder,
        $request->query->getInt('page', 1),
        6
    );
    
    return $this->render('postulation/index2.html.twig', [
       'postulations' => $postulations,
       
    ]);
}
    #[Route('/admin', name: 'display_admin')]
    public function indexAdmin(): Response
    {  
        return $this->render('Admin/index.html.twig'

        );
    }
    
    #[Route('/addPos', name: 'postulation_add')]
    public function addPos(Request $request): Response{
    $entityManager = $this->getDoctrine()->getManager();
    $creator = $entityManager->getRepository(Users::class)->find(1);
    $postulation = new postulation(); 
    
    $form=$this->createForm(posType::class,$postulation);
    $form->handleRequest($request);
     if ($form->isSubmitted()&& $form->isValid()){
        $postulation->setCreator($creator);
        $em= $this->getDoctrine()->getManager();
        $em->persist($postulation);//add
        $em->flush();
        

        return $this->redirectToRoute('display_pos');
     }
     return $this->render('postulation/addPos.html.twig',['form'=>$form->createView()]);

    }  
    #[Route('/removepos/{idPos}', name: 'remove_pos')]
    public function RemovePos(Postulation $postulation): Response
    {  
       $em=$this->getDoctrine()->getManager();
       $em->remove($postulation);
       $em->flush();
       return $this->redirectToRoute('display_pos');
    }
    #[Route('/updatePos/{idPos}', name: 'postulation_update')]
    public function UpdatePos(Request $request,$idPos): Response{
    
    $postulation = $this->getDoctrine()->getManager()->getRepository(Postulation::class)->find($idPos); 
    
    $form=$this->createForm(posType::class,$postulation);
    $form->handleRequest($request);
     if ($form->isSubmitted()&& $form->isValid()){
        $em= $this->getDoctrine()->getManager();
      
        $em->flush();

        return $this->redirectToRoute('display_pos');
     }
     return $this->render('postulation/updatePos.html.twig',['form'=>$form->createView()]);


    }
    
    #[Route('/Admin/postulation/total1', name: 'total_Postulations1')]
    public function getTotalPostulations1(PostulationRepository $PostulationRepository): Response
    {
       
        $totalPostulations = $PostulationRepository->countPostulations();
        $pos=$this->getDoctrine()->getManager()->getRepository(Postulation::class)->findAll();
        return $this->render('postulation/my_postulations.html.twig', [
            'totalPostulations' => $totalPostulations,
            'p'=>$pos
        ]);
    }


    #[Route('/Admin/postulation/total2', name: 'total_Postulations2')]
    public function getTotalPostulations2(PostulationRepository $PostulationRepository): Response
    {
       
        $totalPostulations = $PostulationRepository->countPostulations();
        $pos=$this->getDoctrine()->getManager()->getRepository(Postulation::class)->findAll();
        return $this->render('postulation/showPos.html.twig', [
            'totalPostulations' => $totalPostulations,
            'p'=>$pos
        ]);


    }

#[Route('/pdf',name:'pdfpos')]
public function pdfpos()
{
    
    $pdfOptions = new Options();
    $pdfOptions->set('defaultFont', 'Arial');

    // Instantiate Dompdf with our options
    $dompdf = new Dompdf($pdfOptions);
    
    $pos=$this->getDoctrine()->getManager()->getRepository(Postulation::class)->findAll();

    // Retrieve the HTML generated in our twig file
    $html = $this->renderView('postulation/pdf.html.twig', [   
        'p'=>$pos
       
    ]);

    // Load HTML to Dompdf
    $dompdf->loadHtml($html);

    // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
    $dompdf->setPaper('A4', 'portrait');

    // Render the HTML as PDF
    $dompdf->render();

    // Output the generated PDF to Browser (force download)
    $dompdf->stream("mypdf.pdf", [
        "Attachment" => false
    ]);
}

//#[Route('/search', name: 'search')]
//public function search2(Request $request): Response
//{
   // $form = $this->createForm(SearchType::class);
    //$form->handleRequest($request);
//
    //if ($form->isSubmitted() && $form->isValid()) {
       // $data = $form->getData();
       // $email = $form->get('email')->getData();
       // $creator = $data['creator'];
//
        //$entityManager = $this->getDoctrine()->getManager();
        //$postulationRepository = $entityManager->getRepository(Postulation::class);

        //if ($email!== null) {
          //  $postulations = $postulationRepository->findBy(['email' => $email]);
       // } elseif ($creator !== null) {
          //  $user = $entityManager->getRepository(Users::class)->findOneBy(['nom' => $creator]);
           // if (!$user) {
           //     throw $this->createNotFoundException('No user found for username '.$creator);
          //  }
           // $postulations = $postulationRepository->findBy(['creator' => $user]);
       // } else {
          //  $postulations = $postulationRepository->findAll();
       // }

       // return $this->render('postulation/searchResult.html.twig', [
          //  'postulations' => $postulations,
          //  'form' => $form->createView(),
        //]);
   // }

    //return $this->render('postulation/searchdata.html.twig', [
       // 'form' => $form->createView(),
   // ]);

   #[Route('/search', name: 'search')]
public function search(Request $request): Response
{
    $form = $this->createForm(SearchType::class);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $data = $form->getData();
        $Nom = $data['name'];

        $entityManager = $this->getDoctrine()->getManager();
        $UsersRepository = $entityManager->getRepository(Users::class);
        $user = $UsersRepository->findOneBy(['name' => $Nom]);

        if (!$user) {
            throw $this->createNotFoundException('No user found for name '.$Nom);
        }

        $postulationRepository = $entityManager->getRepository(Postulation::class);
        $postulations = $postulationRepository->findBy(['creator' => $user]);

        return $this->render('postulation/searchResult.html.twig', [
            'postulations' => $postulations,
            'form' => $form->createView(),
        ]);
    }

    return $this->render('postulation/searchdata.html.twig', [
        'form' => $form->createView(),
    ]);
}
private function fonctionLongue(){
    sleep(3);
  return  'brouette';
}
#[Route('/graph', name: 'app_homepage')]
    public function graph(ChartBuilderInterface $chartBuilder): Response
    {
        $chart = $chartBuilder->createChart(Chart::TYPE_LINE);

        $chart->setData([
            'labels' => ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
            'datasets' => [
                [
                    'label' => 'My First dataset',
                    'backgroundColor' => 'rgb(255, 99, 132)',
                    'borderColor' => 'rgb(255, 99, 132)',
                    'data' => [0, 10, 5, 2, 20, 30, 45],
                ],
            ],
        ]);

        $chart->setOptions([
            'scales' => [
                'y' => [
                    'suggestedMin' => 0,
                    'suggestedMax' => 100,
                ],
            ],
        ]);

        return $this->render('postulation/stat.html.twig', [
            'chart' => $chart,
        ]);
    }

    public  function statistiques(){
        return $this->render('postulation/stat.html.twig');
       
    }
    #[Route('/email', name: 'email')]
public function sendEmail(Request $request,MailerInterface $mailer): Response
{
    $form = $this->createForm(ContactType::class);
    $form->handleRequest($request);
    
    // Create a FormView object from the Form object
    $formView = $form->createView();
    if ($form->isSubmitted() && $form->isValid()) {

job4u-postulation-symfony/templates/postulation/QR.html.twig
{% extends 'base1.html.twig' %}

{% block body %}

<div class="example-wrapper">
    <h1>Symfony QR-Code ✅</h1> <hr>

    <div class="row">
        <div class="col-md-6">
            {{ form_start(form) }}
                {{ form_row(form.name, {'attr': {'class': 'form-control', 'placeholder': 'Recherche'}}) }}
                <hr>
                <button type="submit" class="btn btn-success btn-block">Recherche</button>
            {{ form_end(form) }}
        </div>
        <div class="col-md-6">
            {% if qrCode %}
                <img src="{{ qrCode }}" alt="qr-code">
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

job4u-postulation-symfony/templates/postulation/addpos.html.twig
{% extends 'base1.html.twig' %}

{% block body %}
	<div style="align-items: center;justify-content: center;margin-top: 10px; margin-right: 500px;margin-left: 500px;">
		<div class="card">
			<div class="card-body">
				<h5 class="card-title">Create New Postulation</h5>

				<!-- General Form Elements -->
				{{ form_start(form,{attr:{novalidate:'novalidate'}}) }}
            
       
			<label for="inputText" class="col-sm-4 col-form-label">adresse</label>
            <div class="col-sm-10">
                {{ form_widget(form.adresse,{'attr':{'class':'form-control'}}) }}
                
            </div>
            {{ form_errors(form.adresse,{'attr':{'class':'text-danger'}}) }}



        	<label for="inputText" class="col-sm-4 col-form-label">email</label>
            <div class="col-sm-10">
                {{ form_widget(form.email,{'attr':{'class':'form-control'}}) }}
                
            </div>
            {{ form_errors(form.email,{'attr':{'class':'text-danger'}}) }}



        <label for="inputText" class="col-sm-4 col-form-label">date</label>
        <div class="col-sm-10">
            {{ form_widget(form.date_pos,{'attr':{'class':'form-control'}}) }}
            

        </div>
		{{ form_errors(form.date_pos,{'attr':{'class':'text-danger'}}) }}

		<label for="inputText" class="col-sm-4 col-form-label">creator</label>
		<div class="col-sm-10">
			{{ form_widget(form.creator,{'attr':{'class':'form-control'}}) }}
		
		</div>
			{{ form_errors(form.creator,{'attr':{'class':'text-danger'}}) }}


       		 


				<div class="row mb-3">
					<div class="col-sm-10">
						<button type="submit" class="btn btn-primary">Create pos</button>
					</div>
				</div>

				{{ form_end(form) }}
				<!-- End General Form Elements -->

			</div>
		</div>

	</div>
{% endblock %}

job4u-postulation-symfony/templates/postulation/createPos.html.twig
{% extends 'base.html.twig' %}
{% block body %}
   <div class="row">

        <div  style="display: flex;align-items: center;justify-content: center;margin-top: 150px; padding: 10px;">

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Add Postulation</h5>

                    <!-- General Form Elements -->
                    {{ form_start(form,{attr:{novalidate:'novalidate'}}) }}
                    <label for="inputText" class="col-sm-4 col-form-label">email</label>
                        <div class="col-sm-10">
                            {{ form_widget(form.email,{'attr':{'class':'form-control'}}) }}
							
                        </div>
                        {{ form_errors(form.email,{'attr':{'class':'text-danger'}}) }}



                    <label for="inputText" class="col-sm-4 col-form-label">date</label>
                    <div class="col-sm-10">
                        {{ form_widget(form.date_pos,{'attr':{'class':'form-control'}}) }}
                        

                    </div>
                    {{ form_errors(form.date_pos,{'attr':{'class':'text-danger'}}) }}


                <button type="add" class="btn btn-primary">Add</button>
        
                    

                    {{ form_end(form) }}

                </div>
            </div>

        </div>

    </div>


{% endblock %} 

 

job4u-postulation-symfony/templates/postulation/dashboard.html.twig
{% extends 'base1.html.twig' %}
{% block body %}


	<div style="align-items: center;justify-content: center;margin-top: 100px; margin-right: 500px;margin-left: 500px;">
		<div class="card info-card customers-card">


			<div class="card-body">
				<h5 class="card-title">Number of postulations
					<span>| Total</span>
				</h5>

				<div class="d-flex align-items-center">
					<div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
						<i class="bi bi-people"></i>
					</div>
					<div class="ps-3">
						<h6>{{totalPostulations}}</h6>
						

					</div>
				</div>

			</div>
		</div>

	</div>
{% endblock %}

job4u-postulation-symfony/templates/postulation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {% endblock %}

{% block body %}

<div class="row" style="display: flex;align-items: center;justify-content: center;margin-top: 150px;">

    <div class="col-lg-6">

         
            <div class="card-body">
                <a href=><i class="ri-arrow-left-circle-fill" style="font-size: 50px;"></i></a>
                <h5 class="card-title">Liste des postulations</h5>
               

                <!-- Table with stripped rows -->
                <table class="table table-striped">
                    <thead>
                    <tr>    
                    
                    
                    <th>Email </th>
                    <th>Adresse </th>
                    <th>Date </th>
                    <th>User </th>
                    <th>Role </th>
                    
                    </tr>
                    </thead>
                    <tbody>
                        {%for pos in p  %}
                        <tr>
                        
                        
                        <td >{{pos.email}}</td>
                        <td >{{pos.adresse}}</td>
                        <td >{{pos.getDatePos()|date('Y-m-d') }}</td>
                        <td>{{ pos.creator.nom ~ ' ' ~ pos.creator.prenom }}</td>
                        <td>{{ pos.creator.role}}
                        <td>
                            <a href= "{{path('postulation_update' ,{'idPos':pos.idPos})}}">Update </a>
                            </td>
                            <td>
                            <a href= "{{path('remove_pos' ,{'idPos':pos.idPos})}}">Remove </a>
                            </td>
                        </tr>

                    {% endfor %}

                    </tbody>
                </table>
                <!-- End small tables -->

            </div>
        

    </div>



</div>

{% endblock %}

job4u-postulation-symfony/templates/postulation/index2.html.twig
{% extends 'base1.html.twig' %}

{% block title %}Liste des postulations{% endblock %}

{% block body %}
    <h1>Liste des postulations</h1>
    {% for   postulation in postulations %}
    <tr>
                        
                        
    <td >{{postulation.email}}</td>
    <td >{{postulation.getDatePos()|date('Y-m-d') }}</td>
    {% endfor %}

    {{ knp_pagination_render(postulations) }}
{% endblock %}

job4u-postulation-symfony/templates/postulation/mail.html.twig
{% extends 'base1.html.twig'%}
{% block title %}page de contact {% endblock %}
{% block body %}
<h1>
    contactez-nous
</h1>
<div>
    {{form(formulaire)}} </div>
{% endblock %}

job4u-postulation-symfony/templates/postulation/my_postulations.html.twig
{% extends 'base1.html.twig' %}
{% block body %}
	<div class="row" style="margin-left: 50px;margin-right: 50px;">
		<div class="col-lg-12">
			<div class="card">
				<div class="card-body">
					<h5 class="card-title text-dark">List Of The postulations</h5>
					<!-- Table with stripped rows -->
					<div class="dataTable-wrapper dataTable-loading no-footer sortable searchable fixed-columns" style="">
						<div class="dataTable-top">
							<div style="margin-left: 1150px;margin-top: 10px;margin-bottom: 10px;" class="dataTable-search"><input class="dataTable-input" placeholder="Search..." type="text"></div>
						</div>
						<div class="dataTable-container">
							<table class="table datatable dataTable-table">
								<thead>
									<tr>
										<th scope="col" data-sortable="" style="width: 3%;" class="asc">
											<a href="#" class="dataTable-sorter">#</a>
										</th>
										

										<th scope="col" data-sortable="" style="width: 10.7199%;">
											<a href="#" class="dataTable-sorter">email</a>
										</th>
										<th scope="col" data-sortable="" style="width: 11.30311%;">
											<a href="#" class="dataTable-sorter">date</a>
										</th>
						
									</tr>
								</thead>
								<tbody>
							
											{% set i=0 %}
											{% for pos in p %}
												{% set i=i+1 %}
												<tr>
													<th scope="row">{{i}}</th>
                                                    
                        						
												<td >{{pos.email}}</td>
												<td >{{pos.getDatePos()|date('Y-m-d') }}</td>
												
												<td>
												<a href= "{{path('postulation_update' ,{'idPos':pos.idPos})}}">Update </a>
                                                </td>
                                                <td>
                                                <a href= "{{path('remove_pos' ,{'idPos':pos.idPos})}}">Remove </a>
                                                </td>
												<td>
                                                <a href= "{{path('total_Postulations2' ,{'idPos':pos.idPos})}}">show </a>
                                                </td>
							
												
													

													
												</tr>
											{% endfor %}
										
									</tbody>
								</tbody>
							</table>
						</div>
						<div class="dataTable-bottom">
							<nav class="dataTable-pagination">
								<ul class="dataTable-pagination-list"></ul>
							</nav>
						</div>
					</div>
					<!-- End Table with stripped rows -->

				</div>
			</div>

		</div>
	</div>
{% endblock %}

job4u-postulation-symfony/templates/postulation/pagination.html.twig
<div class="pagination">
    <ul>
        {% for   postulation in postulations %}
        {% if postulations.hasPreviousPage %}
            <li><a href="{{path('postulation_update') }}">«</a></li>
        {% endif %}
 
        {% for postulation in postulations.pagesInRange %}
            {% if postulation is same as postulations.currentPageNumber %}
                <li class="active"><a href="#">{{ postulation}}</a></li>
            {% else %}
                <li><a href="{{ path('postulation_update')}}">{{ postulation }}</a></li>
            {% endif %}
        {% endfor %}
 
        {% if postulations.hasNextPage %}
            <li><a href="{{path('remove_pos') }}">»</a></li>
        {% endif %}
    </ul>
</div>

job4u-postulation-symfony/templates/postulation/search.html.twig
{% extends 'base1.html.twig' %}

{% block body %}
    <h1>Search</h1>
    {{ form_start(form) }}
        {{ form_row(form.email) }}
       
        {{ form_row(form.creator) }}
        <button type="submit">Search</button>
    {{ form_end(form) }}

    {% if results is not empty %}
    <h2>Search Results:</h2>
    <ul>
        {% for postulation in results %}
            <li>
                <h3>{{ postulation.email}}</h3>
                
                <p>Creator: {{ postulation.creator.nom }}</p>
               
            </li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock %}

job4u-postulation-symfony/templates/postulation/searchResult.html.twig
{{% extends 'base1.html.twig' %}}

{% block title %}Search Results{% endblock %}

{% block body %}
    <h1>Search Results</h1>
    
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Email</th>
                <th>Creator</th>
                <th>role</th>
            </tr>
        </thead>
        <tbody>
            {% for postulation in postulations %}
                <tr>
                    <td>{{ postulation.idPos }}</td>
                    <td>{{ postulation.email }}</td>
               
                    <td>{{ postulation.creator.Nom}}</td>
                   
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% include 'event/searchdata.html.twig' %}
    <a href="{{ path('search') }}">Back to Search</a>
{% endblock %}

job4u-postulation-symfony/templates/postulation/stat.html.twig
{% include 'base1.html.twig' %}
{{ render_chart(chart) }}

{# You can pass HTML attributes as a second argument to add them on the <canvas> tag #}
{{ render_chart(chart, {'class': 'my-chart'}) }}